application: poetic-avenue-298
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /assets
  static_dir: assets

- url: /bootstrap
  static_dir: bootstrap
  
- url: /tasks/status
  script: handlers/status.py
  
- url: /tasks/flight_radar
  script: handlers/status.py

- url: /joy
  static_dir: joy.js

- url: /game
  script: handlers.game.app

- url: /profile
  script: handlers.game.app  
 
- url: /.*
  script: handlers.main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest

  